a = input('Digite oque deseja saber aqui:')
print('É numero inteiro? {}'.format(a,), a.isnumeric())
print('É uma letra? {}'.format(a,), a.isalpha())
print(f'Só tem espaços? {a.isspace()}')
print(f'O tipo primitivo dele é {type(a)}')
algo2 = input('Digite o que deseja saber: ')
print('é um número inteiro? {}' .format(algo2,), a.isnumeric())
